# Generated by Django 6.0.4 on 2026-05-26 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('imported_file', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('created_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('rxnorm_rxcui', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('atc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('dosage_info', models.TextField(blank=True, null=True)),
                ('adverse_reactions', models.TextField(blank=True, null=True)),
                ('source_name', models.CharField(default='manual', max_length=100)),
                ('source_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('alias_type', models.CharField(choices=[('generic', 'Generic'), ('brand', 'Brand'), ('synonym', 'Synonym'), ('local', 'Local'), ('arabic', 'Arabic'), ('misspelling', 'Misspelling')], max_length=20)),
                ('language', models.CharField(default='en', max_length=20)),
                ('source_name', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='medical_catalog.drug')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
    ]
