# Generated by Django 6.0.4 on 2026-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("pharmacist", "Pharmacist"),
                    ("laboratorian", "Laboratorian"),
                    ("staff", "Staff / Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
