# Generated by Django 6.0.4 on 2026-05-02 15:03

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.upload_paths
import apps.common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medical_license_number", models.CharField(blank=True, max_length=50)),
                (
                    "medical_license_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.doctor_license_upload_path,
                    ),
                ),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("subspecialty", models.CharField(blank=True, max_length=100)),
                ("professional_title", models.CharField(blank=True, max_length=100)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("work_address", models.TextField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
            },
        ),
        migrations.CreateModel(
            name="LaboratorianProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("laboratorian_license_number", models.CharField(blank=True, max_length=50)),
                (
                    "laboratorian_license_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.laboratorian_license_upload_path,
                    ),
                ),
                ("laboratory_name", models.CharField(blank=True, max_length=200)),
                ("laboratory_license_number", models.CharField(blank=True, max_length=50)),
                (
                    "laboratory_license_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.laboratory_license_upload_path,
                    ),
                ),
                ("laboratory_address", models.TextField(blank=True)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("working_hours", models.CharField(blank=True, max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratorian_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratorian Profile",
                "verbose_name_plural": "Laboratorian Profiles",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("social_security_id", models.CharField(blank=True, max_length=30)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=150)),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[apps.common.validators.iraqi_phone_validator],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
            },
        ),
        migrations.CreateModel(
            name="PharmacistProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pharmacist_license_number", models.CharField(blank=True, max_length=50)),
                (
                    "pharmacist_license_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.pharmacist_license_upload_path,
                    ),
                ),
                ("pharmacy_name", models.CharField(blank=True, max_length=200)),
                ("pharmacy_license_number", models.CharField(blank=True, max_length=50)),
                (
                    "pharmacy_license_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.pharmacy_license_upload_path,
                    ),
                ),
                ("pharmacy_address", models.TextField(blank=True)),
                ("working_hours", models.CharField(blank=True, max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacist Profile",
                "verbose_name_plural": "Pharmacist Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[apps.common.validators.iraqi_phone_validator],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.profile_image_upload_path,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "governorate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("baghdad", "Baghdad"),
                            ("basra", "Basra"),
                            ("nineveh", "Nineveh"),
                            ("erbil", "Erbil"),
                            ("najaf", "Najaf"),
                            ("karbala", "Karbala"),
                            ("dhi_qar", "Dhi Qar"),
                            ("maysan", "Maysan"),
                            ("wasit", "Wasit"),
                            ("diyala", "Diyala"),
                            ("anbar", "Anbar"),
                            ("salah_al_din", "Salah al-Din"),
                            ("kirkuk", "Kirkuk"),
                            ("sulaymaniyah", "Sulaymaniyah"),
                            ("dohuk", "Dohuk"),
                            ("qadisiyyah", "Qadisiyyah"),
                            ("muthanna", "Muthanna"),
                            ("babylon", "Babylon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
