# Generated by Django 6.0.4 on 2026-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="specialty_other",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general_medicine", "General Medicine"),
                    ("internal_medicine", "Internal Medicine"),
                    ("cardiology", "Cardiology"),
                    ("dermatology", "Dermatology"),
                    ("pediatrics", "Pediatrics"),
                    ("gynecology", "Gynecology"),
                    ("neurology", "Neurology"),
                    ("ent", "ENT"),
                    ("ophthalmology", "Ophthalmology"),
                    ("orthopedics", "Orthopedics"),
                    ("urology", "Urology"),
                    ("gastroenterology", "Gastroenterology"),
                    ("psychiatry", "Psychiatry"),
                    ("emergency_medicine", "Emergency Medicine"),
                    ("family_medicine", "Family Medicine"),
                    ("dentistry", "Dentistry"),
                    ("endocrinology", "Endocrinology"),
                    ("pulmonology", "Pulmonology"),
                    ("nephrology", "Nephrology"),
                    ("rheumatology", "Rheumatology"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
