# Generated by Django 6.0.4 on 2026-05-15 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_doctorprofile_verified_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_role",
                    models.CharField(
                        choices=[
                            ("system_admin", "System Administrator"),
                            ("verification_officer", "Verification Officer"),
                            ("knowledge_base_manager", "Knowledge Base Manager"),
                            ("analytics_officer", "Analytics Officer"),
                            ("support_specialist", "Support Specialist"),
                            ("compliance_officer", "Compliance Officer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("can_approve_professionals", models.BooleanField(default=False)),
                ("can_manage_knowledge_base", models.BooleanField(default=False)),
                ("can_export_datasets", models.BooleanField(default=False)),
                ("can_view_audit_logs", models.BooleanField(default=False)),
                ("hire_date", models.DateField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivation_reason", models.TextField(blank=True)),
                ("has_completed_training", models.BooleanField(default=False)),
                ("training_completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_supervised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
            },
        ),
    ]
