# Generated by Django 6.0.4 on 2026-05-27 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_currency',
            field=models.CharField(default='IQD', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
