# Generated by Django 6.0.4 on 2026-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_doctorprofile_consultation_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_role",
            field=models.CharField(
                choices=[
                    ("system_admin", "System Administrator"),
                    ("financial", "Financial"),
                    ("verification_officer", "Verification Officer"),
                    ("knowledge_base_manager", "Knowledge Base Manager"),
                    ("analytics_officer", "Analytics Officer"),
                    ("support_specialist", "Support Specialist"),
                    ("compliance_officer", "Compliance Officer"),
                ],
                max_length=50,
            ),
        ),
    ]
