# Generated by Django 6.0.4 on 2026-05-30 10:52

import apps.common.upload_paths
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_staffprofile_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboratorianprofile",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="laboratorianprofile",
            name="laboratory_governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("baghdad", "Baghdad"),
                    ("basra", "Basra"),
                    ("nineveh", "Nineveh"),
                    ("erbil", "Erbil"),
                    ("najaf", "Najaf"),
                    ("karbala", "Karbala"),
                    ("dhi_qar", "Dhi Qar"),
                    ("maysan", "Maysan"),
                    ("wasit", "Wasit"),
                    ("diyala", "Diyala"),
                    ("anbar", "Anbar"),
                    ("salah_al_din", "Salah al-Din"),
                    ("kirkuk", "Kirkuk"),
                    ("sulaymaniyah", "Sulaymaniyah"),
                    ("dohuk", "Dohuk"),
                    ("qadisiyyah", "Qadisiyyah"),
                    ("muthanna", "Muthanna"),
                    ("babylon", "Babylon"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="laboratorianprofile",
            name="laboratory_phone_number",
            field=models.CharField(
                blank=True, max_length=11, validators=[apps.common.validators.iraqi_phone_validator]
            ),
        ),
        migrations.AddField(
            model_name="laboratorianprofile",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="laboratorianprofile",
            name="working_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="national_id_back_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.upload_paths.national_id_back_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="national_id_front_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.upload_paths.national_id_front_upload_path,
            ),
        ),
    ]
