# Generated by Django 6.0.4 on 2026-05-03 15:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodGroupRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("a_positive", "A+"),
                            ("a_negative", "A-"),
                            ("b_positive", "B+"),
                            ("b_negative", "B-"),
                            ("ab_positive", "AB+"),
                            ("ab_negative", "AB-"),
                            ("o_positive", "O+"),
                            ("o_negative", "O-"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("self_reported", "Self Reported"),
                            ("doctor_confirmed", "Doctor Confirmed"),
                            ("laboratory_confirmed", "Laboratory Confirmed"),
                            ("rejected", "Rejected"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_group_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_group_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_group_record",
                        to="patient_records.patientmedicalrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("blood_group", "Blood Group"),
                            ("allergy", "Allergy"),
                            ("chronic_condition", "Chronic Condition"),
                            ("current_medication", "Current Medication"),
                            ("past_surgery", "Past Surgery"),
                            ("family_history", "Family History"),
                            ("smoking_status", "Smoking Status"),
                            ("pregnancy_status", "Pregnancy Status"),
                            ("general_note", "General Note"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("self_reported", "Self Reported"),
                            ("doctor_confirmed", "Doctor Confirmed"),
                            ("laboratory_confirmed", "Laboratory Confirmed"),
                            ("rejected", "Rejected"),
                            ("unknown", "Unknown"),
                        ],
                        default="self_reported",
                        max_length=30,
                    ),
                ),
                (
                    "source_role",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("doctor", "Doctor"),
                            ("laboratorian", "Laboratorian"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_medical_record_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_medical_record_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="patient_records.patientmedicalrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["medical_record", "is_active"],
                        name="patient_rec_medical_59090a_idx",
                    ),
                    models.Index(
                        fields=["medical_record", "category"], name="patient_rec_medical_3dc6c4_idx"
                    ),
                    models.Index(
                        fields=["verification_status"], name="patient_rec_verific_e6548f_idx"
                    ),
                ],
            },
        ),
    ]
