# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["medical_record", "is_active", "-created_at"],
                name="patient_rec_medical_75d2d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["source_user", "-created_at"], name="patient_rec_source__bac879_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["verified_by", "-created_at"], name="patient_rec_verifie_a60707_idx"
            ),
        ),
    ]
