# Generated by Django 6.0.4 on 2026-05-23 15:50

import apps.common.upload_paths
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_consultation_recommended_specialties"),
        ("messaging", "0002_consultationmessage_messaging_c_consult_0503f2_idx_and_more"),
        ("patient_records", "0002_medicalrecordentry_patient_rec_medical_75d2d1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecordentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("blood_group", "Blood Group"),
                    ("allergy", "Allergy"),
                    ("chronic_condition", "Chronic Condition"),
                    ("current_medication", "Current Medication"),
                    ("past_surgery", "Past Surgery"),
                    ("family_history", "Family History"),
                    ("smoking_status", "Smoking Status"),
                    ("pregnancy_status", "Pregnancy Status"),
                    ("general_note", "General Note"),
                    ("lab_report", "Lab Report"),
                    ("sonar_report", "Sonar Report"),
                    ("xray_report", "X-Ray Report"),
                    ("radiology_report", "Radiology Report"),
                    ("prescription_report", "Prescription Report"),
                    ("discharge_summary", "Discharge Summary"),
                    ("uploaded_medical_report", "Uploaded Medical Report"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PatientMedicalReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("chat_attachment", "Chat Attachment"),
                            ("consultation_attachment", "Consultation Attachment"),
                            ("lab_result_file", "Lab Result File"),
                            ("manual_upload", "Manual Upload"),
                            ("system_import", "System Import"),
                        ],
                        default="chat_attachment",
                        max_length=40,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("lab_report", "Lab Report"),
                            ("sonar_report", "Sonar Report"),
                            ("xray_report", "X-Ray Report"),
                            ("ct_scan", "CT Scan"),
                            ("mri", "MRI"),
                            ("ecg", "ECG"),
                            ("prescription_image", "Prescription Image"),
                            ("discharge_summary", "Discharge Summary"),
                            ("doctor_note", "Doctor Note"),
                            ("pathology_report", "Pathology Report"),
                            ("microbiology_report", "Microbiology Report"),
                            ("radiology_report", "Radiology Report"),
                            ("other_medical_report", "Other Medical Report"),
                            ("not_medical_report", "Not Medical Report"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=40,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("queued", "Queued"),
                            ("ocr_pending", "OCR Pending"),
                            ("ocr_completed", "OCR Completed"),
                            ("llm_pending", "LLM Pending"),
                            ("llm_completed", "LLM Completed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("doctor_reviewed", "Doctor Reviewed"),
                        ],
                        default="uploaded",
                        max_length=40,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("patient_and_assigned_doctor", "Patient and Assigned Doctor"),
                            ("doctor_only", "Doctor Only"),
                            ("staff_only", "Staff Only"),
                        ],
                        default="patient_and_assigned_doctor",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.upload_paths.medical_report_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("raw_ocr_text", models.TextField(blank=True)),
                ("cleaned_report_text", models.TextField(blank=True)),
                ("structured_payload", models.JSONField(blank=True, default=dict)),
                ("removed_noise_summary", models.JSONField(blank=True, default=list)),
                ("detected_language", models.CharField(blank=True, max_length=50)),
                (
                    "llm_confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("is_medical_report", models.BooleanField(default=False)),
                ("rejection_reason", models.CharField(blank=True, max_length=120)),
                ("processing_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_reports",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "linked_medical_record_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_medical_reports",
                        to="patient_records.medicalrecordentry",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_medical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_reports",
                        to="messaging.messageattachment",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_reports",
                        to="messaging.consultationmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"], name="patient_rec_patient_cd3e06_idx"
                    ),
                    models.Index(
                        fields=["consultation", "-created_at"],
                        name="patient_rec_consult_16e4c3_idx",
                    ),
                    models.Index(
                        fields=["source_attachment"], name="patient_rec_source__2a497e_idx"
                    ),
                    models.Index(fields=["report_type"], name="patient_rec_report__027b7a_idx"),
                    models.Index(
                        fields=["processing_status"], name="patient_rec_process_10a6a8_idx"
                    ),
                    models.Index(
                        fields=["is_medical_report"], name="patient_rec_is_medi_63a8d7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_attachment__isnull", False)),
                        fields=("source_attachment",),
                        name="uniq_medical_report_source_attachment",
                    )
                ],
            },
        ),
    ]
