# Generated by Django 6.0.4 on 2026-05-03 15:35

import apps.common.upload_paths
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_orders', '0001_initial'),
        ('patient_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('released', 'Released'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric'), ('positive_negative', 'Positive / Negative'), ('blood_group', 'Blood Group'), ('file_only', 'File Only')], max_length=30)),
                ('text_value', models.TextField(blank=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('blood_group_value', models.CharField(blank=True, choices=[('a_positive', 'A+'), ('a_negative', 'A-'), ('b_positive', 'B+'), ('b_negative', 'B-'), ('ab_positive', 'AB+'), ('ab_negative', 'AB-'), ('o_positive', 'O+'), ('o_negative', 'O-'), ('unknown', 'Unknown')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critical Low'), ('critical_high', 'Critical High'), ('abnormal', 'Abnormal'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to=apps.common.upload_paths.lab_result_file_upload_path)),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('laboratorian_notes', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_linked_to_medical_record', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_lab_results', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab_orders.laborder')),
                ('lab_order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab_orders.laborderitem')),
                ('laboratorian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lab_results', to=settings.AUTH_USER_MODEL)),
                ('linked_blood_group_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_results', to='patient_records.bloodgrouprecord')),
                ('linked_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_results', to='patient_records.medicalrecordentry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResultCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_result_corrections', to=settings.AUTH_USER_MODEL)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='lab_orders.labresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
