# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_consultation_consultatio_patient_1ac522_idx_and_more"),
        ("lab_orders", "0002_labresult_labresultcorrection"),
        ("patient_records", "0002_medicalrecordentry_patient_rec_medical_75d2d1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="labcompletionrecord",
            index=models.Index(
                fields=["lab_order", "-created_at"], name="lab_orders__lab_ord_6f9334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labcompletionrecord",
            index=models.Index(
                fields=["laboratorian", "-created_at"], name="lab_orders__laborat_54ea4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["patient", "-created_at"], name="lab_orders__patient_6aebe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["doctor", "-created_at"], name="lab_orders__doctor__c8f29b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["status", "-created_at"], name="lab_orders__status_2438d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["expires_at"], name="lab_orders__expires_f4de64_idx"),
        ),
        migrations.AddIndex(
            model_name="laborderitem",
            index=models.Index(
                fields=["lab_order", "status", "created_at"], name="lab_orders__lab_ord_dd0e33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["patient", "-created_at"], name="lab_orders__patient_721a47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["doctor", "-created_at"], name="lab_orders__doctor__e78d72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["laboratorian", "-created_at"], name="lab_orders__laborat_ec3622_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["status", "-created_at"], name="lab_orders__status_25aea0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(fields=["released_at"], name="lab_orders__release_94642d_idx"),
        ),
        migrations.AddIndex(
            model_name="labresultcorrection",
            index=models.Index(
                fields=["lab_result", "-created_at"], name="lab_orders__lab_res_b89ca6_idx"
            ),
        ),
    ]
