# Generated by Django 6.0.4 on 2026-05-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_catalog', '0001_initial'),
        ('lab_orders', '0003_labcompletionrecord_lab_orders__lab_ord_6f9334_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborderitem',
            name='custom_test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order_items', to='lab_catalog.labtest'),
        ),
    ]
