# Generated by Django 6.0.4 on 2026-05-26 12:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_catalog", "0001_initial"),
        ("profiles", "0004_staffprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyDrugInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_drug_name", models.CharField(blank=True, max_length=255, null=True)),
                ("brand_name", models.CharField(blank=True, max_length=255, null=True)),
                ("form", models.CharField(blank=True, max_length=100, null=True)),
                ("strength", models.CharField(blank=True, max_length=100, null=True)),
                ("route", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="IQD", max_length=10)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_inventory_items",
                        to="medical_catalog.drug",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="profiles.pharmacistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["pharmacy", "is_active"], name="pharmacy_in_pharmac_17f066_idx"
                    ),
                    models.Index(
                        fields=["stock_status", "is_available"],
                        name="pharmacy_in_stock_s_6bf119_idx",
                    ),
                    models.Index(fields=["drug"], name="pharmacy_in_drug_id_889333_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("drug__isnull", False), ("is_active", True)),
                        fields=("pharmacy", "drug"),
                        name="uniq_active_inventory_pharmacy_drug",
                    )
                ],
            },
        ),
    ]
