# Generated by Django 6.0.4 on 2026-05-03 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('partially_dispensed', 'Partially Dispensed'), ('fully_dispensed', 'Fully Dispensed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='issued', max_length=30)),
                ('qr_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('qr_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fully_dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='consultations.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('injection', 'Injection'), ('eye', 'Eye'), ('ear', 'Ear'), ('nasal', 'Nasal'), ('rectal', 'Rectal'), ('other', 'Other')], max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('dispensed', 'Dispensed'), ('unavailable', 'Unavailable')], max_length=20)),
                ('dispensed_quantity', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_records', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='prescriptions.prescription')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
