# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_consultation_consultatio_patient_1ac522_idx_and_more"),
        ("prescriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dispensingrecord",
            index=models.Index(
                fields=["prescription", "-created_at"], name="prescriptio_prescri_1075c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispensingrecord",
            index=models.Index(
                fields=["pharmacist", "-created_at"], name="prescriptio_pharmac_82332f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-created_at"], name="prescriptio_patient_d016dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["doctor", "-created_at"], name="prescriptio_doctor__b1eceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["status", "-created_at"], name="prescriptio_status_565a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["expires_at"], name="prescriptio_expires_fcdd44_idx"),
        ),
        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["prescription", "status", "created_at"],
                name="prescriptio_prescri_8c10bd_idx",
            ),
        ),
    ]
