# Generated by Django 6.0.4 on 2026-05-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_catalog", "0001_initial"),
        ("prescriptions", "0002_dispensingrecord_prescriptio_prescri_1075c1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="custom_drug_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="drug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescription_items",
                to="medical_catalog.drug",
            ),
        ),
    ]
