# Generated by Django 6.0.4 on 2026-05-26 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCatalogImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('imported_file', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('created_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('loinc_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('system', models.CharField(blank=True, max_length=150, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=150, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('source_name', models.CharField(default='manual', max_length=100)),
                ('source_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('alias_type', models.CharField(choices=[('short_name', 'Short Name'), ('synonym', 'Synonym'), ('local', 'Local'), ('arabic', 'Arabic'), ('misspelling', 'Misspelling')], max_length=20)),
                ('language', models.CharField(default='en', max_length=20)),
                ('source_name', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='lab_catalog.labtest')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='LabTestClinicalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose_summary', models.TextField(blank=True, null=True)),
                ('patient_preparation', models.TextField(blank=True, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_collection_notes', models.TextField(blank=True, null=True)),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('interpretation_summary', models.TextField(blank=True, null=True)),
                ('interfering_factors', models.TextField(blank=True, null=True)),
                ('safety_notes', models.TextField(blank=True, null=True)),
                ('patient_explanation', models.TextField(blank=True, null=True)),
                ('provider_notes', models.TextField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(default='manual', max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_chunk_ids', models.JSONField(blank=True, default=list)),
                ('source_page_numbers', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_info', to='lab_catalog.labtest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_clinical_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
