# Generated by Django 6.0.4 on 2026-05-02 21:43

import apps.common.upload_paths
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Symptom Category',
                'verbose_name_plural': 'Symptom Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('doctor_responded', 'Doctor Responded'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('recommended_specialty', models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('dentistry', 'Dentistry'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('other', 'Other')], max_length=50, null=True)),
                ('selected_specialty', models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('dentistry', 'Dentistry'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('other', 'Other')], max_length=50, null=True)),
                ('selected_specialty_other', models.CharField(blank=True, max_length=150)),
                ('ai_predicted_specialty', models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('dentistry', 'Dentistry'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('other', 'Other')], max_length=50, null=True)),
                ('ai_predicted_specialty_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_predicted_disease', models.CharField(blank=True, max_length=255)),
                ('ai_predicted_disease_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_prediction_notes', models.TextField(blank=True)),
                ('duration', models.CharField(choices=[('less_than_24_hours', 'Less than 24 hours'), ('one_to_three_days', '1-3 days'), ('four_to_seven_days', '4-7 days'), ('one_to_two_weeks', '1-2 weeks'), ('more_than_two_weeks', 'More than 2 weeks'), ('chronic_recurring', 'Chronic / recurring')], max_length=40)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('very_severe', 'Very severe')], max_length=20)),
                ('has_fever', models.BooleanField(default=False)),
                ('has_pain', models.BooleanField(default=False)),
                ('has_breathing_difficulty', models.BooleanField(default=False)),
                ('has_emergency_warning', models.BooleanField(default=False)),
                ('previous_visit_for_same_issue', models.BooleanField(default=False)),
                ('current_medications_related', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.common.upload_paths.consultation_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.consultation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_text', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('general_advice', 'General Advice'), ('needs_in_person_visit', 'Needs In-Person Visit'), ('needs_emergency_care', 'Needs Emergency Care'), ('needs_lab_test', 'Needs Lab Test'), ('follow_up_required', 'Follow-Up Required')], max_length=40)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='consultations.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_red_flag', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='consultations.symptomcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomSpecialtyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('dentistry', 'Dentistry'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('other', 'Other')], max_length=50)),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_rules', to='consultations.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_symptoms', to='consultations.consultation')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_links', to='consultations.symptom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consultation', 'symptom'), name='uniq_consultation_symptom')],
            },
        ),
        migrations.AddConstraint(
            model_name='symptom',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_symptom_category_name'),
        ),
        migrations.AddConstraint(
            model_name='symptomspecialtyrule',
            constraint=models.UniqueConstraint(fields=('symptom', 'specialty'), name='uniq_symptom_specialty_rule'),
        ),
    ]
