# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["patient", "-created_at"], name="consultatio_patient_1ac522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["assigned_doctor", "-created_at"], name="consultatio_assigne_f94298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["status", "-created_at"], name="consultatio_status_49d4ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["selected_specialty", "status", "-created_at"],
                name="consultatio_selecte_7c54d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationresponse",
            index=models.Index(
                fields=["consultation", "-created_at"], name="consultatio_consult_fdb724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultationresponse",
            index=models.Index(
                fields=["doctor", "-created_at"], name="consultatio_doctor__514cbf_idx"
            ),
        ),
    ]
