# Generated by Django 6.0.4 on 2026-05-22 00:00

from django.db import migrations, models


def backfill_recommended_specialties(apps, schema_editor):
    Consultation = apps.get_model("consultations", "Consultation")

    for consultation in Consultation.objects.all().only(
        "id",
        "recommended_specialty",
        "selected_specialty",
        "recommended_specialties",
    ):
        ranked_specialties = []
        for specialty in [consultation.selected_specialty, consultation.recommended_specialty]:
            if specialty and specialty not in ranked_specialties:
                ranked_specialties.append(specialty)

        consultation.recommended_specialties = ranked_specialties
        consultation.save(update_fields=["recommended_specialties"])


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_consultation_consultatio_patient_1ac522_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="recommended_specialties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            backfill_recommended_specialties,
            migrations.RunPython.noop,
        ),
    ]