# Generated by Django 6.0.4 on 2026-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_recommended_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_currency',
            field=models.CharField(default='IQD', max_length=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='fee_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
