# Generated by Django 6.0.4 on 2026-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("account", "Account"),
                    ("profile", "Profile"),
                    ("medical_record", "Medical Record"),
                    ("consultation", "Consultation"),
                    ("message", "Message"),
                    ("prescription", "Prescription"),
                    ("dispensing", "Dispensing"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
