# Generated by Django 6.0.4 on 2026-05-26 13:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pharmacy_inventory", "0001_initial"),
        ("prescriptions", "0003_prescriptionitem_custom_drug_name_and_more"),
        ("profiles", "0004_staffprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyPrescriptionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("currency", models.CharField(default="IQD", max_length=10)),
                ("pharmacy_notes", models.TextField(blank=True, null=True)),
                ("patient_notes", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_prescription_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_requests",
                        to="profiles.pharmacistprofile",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_requests",
                        to="prescriptions.prescription",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_pharmacy_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyPrescriptionRequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_name_snapshot", models.CharField(max_length=255)),
                ("quoted_name", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("substituted", "Substituted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("substitution_note", models.TextField(blank=True, null=True)),
                ("pharmacy_note", models.TextField(blank=True, null=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_items",
                        to="pharmacy_inventory.pharmacydruginventory",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_request_items",
                        to="prescriptions.prescriptionitem",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy_requests.pharmacyprescriptionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pharmacyprescriptionrequest",
            index=models.Index(
                fields=["status", "created_at"], name="pharmacy_re_status_08ee2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacyprescriptionrequest",
            index=models.Index(
                fields=["prescription", "pharmacy"], name="pharmacy_re_prescri_a534e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacyprescriptionrequest",
            index=models.Index(
                fields=["patient", "created_at"], name="pharmacy_re_patient_0cf9f1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacyprescriptionrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "quoted"])),
                fields=("prescription", "pharmacy"),
                name="uniq_active_pending_quoted_prescription_pharmacy_request",
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacyprescriptionrequestitem",
            index=models.Index(
                fields=["request", "availability_status"], name="pharmacy_re_request_ca5495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacyprescriptionrequestitem",
            index=models.Index(fields=["prescription_item"], name="pharmacy_re_prescri_a14b50_idx"),
        ),
        migrations.AddConstraint(
            model_name="pharmacyprescriptionrequestitem",
            constraint=models.UniqueConstraint(
                fields=("request", "prescription_item"), name="uniq_request_prescription_item"
            ),
        ),
    ]
