# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_consultation_consultatio_patient_1ac522_idx_and_more"),
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="consultationmessage",
            index=models.Index(
                fields=["consultation", "created_at"], name="messaging_c_consult_0503f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultationmessage",
            index=models.Index(
                fields=["consultation", "is_read", "created_at"],
                name="messaging_c_consult_2cfe32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationmessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="messaging_c_sender__52ff7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["message", "created_at"], name="messaging_m_message_747332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["uploaded_by", "-created_at"], name="messaging_m_uploade_9b42b2_idx"
            ),
        ),
    ]
