# Generated by Django 6.0.4 on 2026-05-26 16:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_inventory', '0001_initial'),
        ('lab_orders', '0004_laborderitem_custom_test_name_laborderitem_lab_test'),
        ('profiles', '0004_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='IQD', max_length=10)),
                ('lab_notes', models.TextField(blank=True, null=True)),
                ('patient_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_order_requests', to='profiles.laboratorianprofile')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='lab_orders.laborder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_order_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_name_snapshot', models.CharField(max_length=255)),
                ('quoted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('availability_status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('substituted', 'Substituted')], default='pending', max_length=20)),
                ('substitution_note', models.TextField(blank=True, null=True)),
                ('lab_note', models.TextField(blank=True, null=True)),
                ('lab_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_request_items', to='lab_orders.laborderitem')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='lab_inventory.labtestoffering')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab_requests.laborderrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='laborderrequest',
            index=models.Index(fields=['status', 'created_at'], name='lab_request_status_d981de_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderrequest',
            index=models.Index(fields=['lab_order', 'lab'], name='lab_request_lab_ord_aeaee6_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderrequest',
            index=models.Index(fields=['patient', 'created_at'], name='lab_request_patient_45ed0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborderrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'quoted'])), fields=('lab_order', 'lab'), name='uniq_active_pending_quoted_laborder_lab_request'),
        ),
        migrations.AddConstraint(
            model_name='laborderrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['accepted', 'completed'])), fields=('lab_order',), name='uniq_accepted_completed_lab_request_per_order'),
        ),
        migrations.AddIndex(
            model_name='laborderrequestitem',
            index=models.Index(fields=['request', 'availability_status'], name='lab_request_request_7d4d82_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderrequestitem',
            index=models.Index(fields=['lab_order_item'], name='lab_request_lab_ord_3b5916_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborderrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'lab_order_item'), name='uniq_lab_request_lab_order_item'),
        ),
    ]
