# Generated by Django 6.0.4 on 2026-05-27 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_orders", "0004_laborderitem_custom_test_name_laborderitem_lab_test"),
        ("lab_requests", "0001_initial"),
        ("payments", "0001_initial"),
        ("profiles", "0005_doctorprofile_consultation_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="laborderrequest",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="laborderrequest",
            name="payment_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="laborderrequest",
            name="payment_intent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="payments.paymentintent",
            ),
        ),
        migrations.AddField(
            model_name="laborderrequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("payment_pending", "Payment Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="laborderrequest",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="laborderrequest",
            index=models.Index(
                fields=["payment_status", "created_at"], name="lab_request_payment_3a4240_idx"
            ),
        ),
    ]
