# Generated by Django 6.0.4 on 2026-05-26 14:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_catalog', '0001_initial'),
        ('profiles', '0004_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('local_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_type_override', models.CharField(blank=True, max_length=150, null=True)),
                ('preparation_notes', models.TextField(blank=True, null=True)),
                ('estimated_turnaround_time', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='IQD', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_offerings', to='profiles.laboratorianprofile')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_offerings', to='lab_catalog.labtest')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['lab', 'is_active'], name='lab_invento_lab_id_314c20_idx'), models.Index(fields=['is_available', 'is_active'], name='lab_invento_is_avai_b8dfb1_idx'), models.Index(fields=['lab_test'], name='lab_invento_lab_tes_b0b8e7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('lab_test__isnull', False)), fields=('lab', 'lab_test'), name='uniq_active_lab_offering_lab_labtest')],
            },
        ),
    ]
