# Generated by Django 6.0.4 on 2026-05-04 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0003_add_embedding_fields_to_chunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_context', models.CharField(choices=[('general_doctor_query', 'General Doctor Query'), ('consultation', 'Consultation'), ('lab_result', 'Lab Result'), ('medical_record', 'Medical Record'), ('prescription', 'Prescription'), ('lab_order', 'Lab Order')], max_length=30)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('query_text', models.TextField()),
                ('role_context', models.CharField(default='doctor', max_length=50)),
                ('top_k', models.PositiveSmallIntegerField(default=6)),
                ('filters', models.JSONField(default=dict)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Query',
                'verbose_name_plural': 'RAG Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_text', models.TextField()),
                ('provider', models.CharField(default='deepseek', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_context', 'No Context'), ('blocked', 'Blocked')], max_length=20)),
                ('safety_level', models.CharField(choices=[('doctor_only', 'Doctor Only'), ('patient_safe', 'Patient Safe'), ('unsafe', 'Unsafe')], default='doctor_only', max_length=20)),
                ('doctor_review_required', models.BooleanField(default=True)),
                ('patient_visible', models.BooleanField(default=False)),
                ('prompt_text', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('token_input', models.PositiveIntegerField(blank=True, null=True)),
                ('token_output', models.PositiveIntegerField(blank=True, null=True)),
                ('rag_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='rag.ragquery')),
            ],
            options={
                'verbose_name': 'RAG Response',
                'verbose_name_plural': 'RAG Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGRetrievedChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rag_retrievals', to='knowledge_base.knowledgechunk')),
                ('rag_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_chunks', to='rag.ragquery')),
            ],
            options={
                'verbose_name': 'RAG Retrieved Chunk',
                'verbose_name_plural': 'RAG Retrieved Chunks',
                'ordering': ['rag_query', 'rank'],
            },
        ),
    ]
