# Generated by Django 6.0.4 on 2026-05-04 01:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGResponseFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("partially_helpful", "Partially Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("unsafe", "Unsafe"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("is_source_grounded", models.BooleanField(blank=True, null=True)),
                ("is_clinically_useful", models.BooleanField(blank=True, null=True)),
                ("is_safe", models.BooleanField(default=True)),
                ("needs_admin_review", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rag_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rag_response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="rag.ragresponse",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_rag_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Response Feedback",
                "verbose_name_plural": "RAG Response Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RAGRetrievedChunkFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relevance",
                    models.CharField(
                        choices=[
                            ("relevant", "Relevant"),
                            ("partially_relevant", "Partially Relevant"),
                            ("not_relevant", "Not Relevant"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=25,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_feedback",
                        to="rag.ragresponsefeedback",
                    ),
                ),
                (
                    "retrieved_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to="rag.ragretrievedchunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Retrieved Chunk Feedback",
                "verbose_name_plural": "RAG Retrieved Chunk Feedbacks",
                "ordering": ["feedback", "retrieved_chunk__rank"],
                "unique_together": {("feedback", "retrieved_chunk")},
            },
        ),
    ]
