# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0004_knowledgechunk_knowledge_b_documen_2f3de1_idx_and_more"),
        ("rag", "0002_ragresponsefeedback_ragretrievedchunkfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ragquery",
            index=models.Index(
                fields=["requested_by", "-created_at"], name="rag_ragquer_request_c061b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragquery",
            index=models.Index(
                fields=["service_context", "-created_at"], name="rag_ragquer_service_928528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragquery",
            index=models.Index(
                fields=["service_context", "object_id", "-created_at"],
                name="rag_ragquer_service_34ff75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ragresponsefeedback",
            index=models.Index(
                fields=["doctor", "-created_at"], name="rag_ragresp_doctor__63fd84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragresponsefeedback",
            index=models.Index(
                fields=["review_status", "-created_at"], name="rag_ragresp_review__3bac20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragresponsefeedback",
            index=models.Index(
                fields=["needs_admin_review", "-created_at"], name="rag_ragresp_needs_a_287738_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragresponsefeedback",
            index=models.Index(
                fields=["rating", "-created_at"], name="rag_ragresp_rating_9e04ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragretrievedchunk",
            index=models.Index(fields=["rag_query", "rank"], name="rag_ragretr_rag_que_0fbb69_idx"),
        ),
        migrations.AddIndex(
            model_name="ragretrievedchunk",
            index=models.Index(
                fields=["chunk", "-created_at"], name="rag_ragretr_chunk_i_b6c9fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragretrievedchunkfeedback",
            index=models.Index(
                fields=["feedback", "retrieved_chunk"], name="rag_ragretr_feedbac_b7cda9_idx"
            ),
        ),
    ]
