# Generated by Django 6.0.4 on 2026-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0003_ragquery_rag_ragquer_request_c061b7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragquery",
            name="service_context",
            field=models.CharField(
                choices=[
                    ("general_doctor_query", "General Doctor Query"),
                    ("consultation", "Consultation"),
                    ("lab_result", "Lab Result"),
                    ("report_case_update", "Report Case Update"),
                    ("medical_record", "Medical Record"),
                    ("prescription", "Prescription"),
                    ("lab_order", "Lab Order"),
                ],
                max_length=30,
            ),
        ),
    ]
