# Generated by Django 6.0.4 on 2026-05-23 17:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0003_consultation_recommended_specialties"),
        ("patient_records", "0003_alter_medicalrecordentry_category_and_more"),
        ("rag", "0004_alter_ragquery_service_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorAIAssistantMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("medical_report_case_update", "Medical Report Case Update"),
                            ("manual_rag_case_update", "Manual RAG Case Update"),
                            ("consultation_context_update", "Consultation Context Update"),
                            ("lab_result_context_update", "Lab Result Context Update"),
                            ("system", "System"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("unread", "Unread"), ("read", "Read"), ("archived", "Archived")],
                        default="unread",
                        max_length=20,
                    ),
                ),
                (
                    "safety_level",
                    models.CharField(
                        choices=[
                            ("doctor_only", "Doctor Only"),
                            ("needs_review", "Needs Review"),
                            ("low_confidence", "Low Confidence"),
                            ("no_context", "No Context"),
                            ("failed", "Failed"),
                        ],
                        default="doctor_only",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_ai_messages",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_ai_assistant_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_ai_case_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_medical_record_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_ai_messages",
                        to="patient_records.medicalrecordentry",
                    ),
                ),
                (
                    "source_rag_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_ai_messages",
                        to="rag.ragresponse",
                    ),
                ),
                (
                    "source_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_ai_messages",
                        to="patient_records.patientmedicalreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consultation", "doctor", "-created_at"],
                        name="rag_doctora_consult_9c114c_idx",
                    ),
                    models.Index(
                        fields=["doctor", "status", "-created_at"],
                        name="rag_doctora_doctor__2fce08_idx",
                    ),
                    models.Index(fields=["source_report"], name="rag_doctora_source__49bc49_idx"),
                    models.Index(
                        fields=["source_rag_response"], name="rag_doctora_source__f2f730_idx"
                    ),
                    models.Index(
                        fields=["trigger_type", "-created_at"],
                        name="rag_doctora_trigger_f2d2ca_idx",
                    ),
                ],
            },
        ),
    ]
