# Generated by Django 6.0.4 on 2026-05-03 19:01

import apps.common.upload_paths
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('medical_book', 'Medical Book'), ('laboratory_book', 'Laboratory Book'), ('clinical_guideline', 'Clinical Guideline'), ('drug_reference', 'Drug Reference'), ('patient_education', 'Patient Education'), ('platform_policy', 'Platform Policy'), ('other', 'Other')], max_length=50)),
                ('language', models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('kurdish', 'Kurdish'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=20)),
                ('audience', models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('laboratorian', 'Laboratorian'), ('patient', 'Patient'), ('admin', 'Admin'), ('mixed', 'Mixed')], max_length=20)),
                ('specialty', models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('internal_medicine', 'Internal Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('neurology', 'Neurology'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('urology', 'Urology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('dentistry', 'Dentistry'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('other', 'Other')], max_length=50, null=True)),
                ('source_authority', models.CharField(blank=True, max_length=300, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.common.upload_paths.knowledge_document_upload_path)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracted', 'Extracted'), ('chunked', 'Chunked'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocumentText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_metadata', models.JSONField(default=dict)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge Document Text',
                'verbose_name_plural': 'Knowledge Document Texts',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge Processing Log',
                'verbose_name_plural': 'Knowledge Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=500, null=True)),
                ('token_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge Chunk',
                'verbose_name_plural': 'Knowledge Chunks',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
