# Generated by Django 6.0.4 on 2026-05-06 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0003_add_embedding_fields_to_chunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["document", "is_active", "chunk_index"],
                name="knowledge_b_documen_2f3de1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["is_active", "-created_at"], name="knowledge_b_is_acti_942020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["approval_status", "-created_at"], name="knowledge_b_approva_952749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["processing_status", "-created_at"], name="knowledge_b_process_15b56c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["document_type", "-created_at"], name="knowledge_b_documen_dd0d17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["specialty", "-created_at"], name="knowledge_b_special_e82b04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["is_active", "-created_at"], name="knowledge_b_is_acti_d7b4f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeprocessinglog",
            index=models.Index(
                fields=["document", "-created_at"], name="knowledge_b_documen_2456bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeprocessinglog",
            index=models.Index(
                fields=["action", "status", "-created_at"], name="knowledge_b_action_65400c_idx"
            ),
        ),
    ]
