# Generated by Django 6.0.4 on 2026-05-06 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0004_knowledgechunk_knowledge_b_documen_2f3de1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="security_status",
            field=models.CharField(
                choices=[
                    ("pending_scan", "Pending Scan"),
                    ("scan_clean", "Scan Clean"),
                    ("scan_failed", "Scan Failed"),
                    ("scan_skipped", "Scan Skipped"),
                ],
                default="scan_skipped",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["security_status", "-created_at"], name="knowledge_b_securit_fbe8f2_idx"
            ),
        ),
    ]
