services:
  db:
    image: pgvector/pgvector:pg16
    container_name: alrafidain_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: alrafidain_db
      POSTGRES_USER: alrafidain_user
      POSTGRES_PASSWORD: alrafidain_password
    ports:
      - "5433:5432"
    volumes:
      - alrafidain_postgres_data:/var/lib/postgresql/data

volumes:
  alrafidain_postgres_data: