# Generated by Django 6.0.4 on 2026-05-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_auditlog_audit_audit_actor_i_1175ab_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="current_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
